### ISSUE TITLE
[PreserveName] attribute is ignored

### ISSUE THREAD

**Issue by guidoren** [andry-tino/Rosetta#29]
The definition runner ignores the `[PreserveName]` attribute.

```
public static class Example
{
  [PreserveName]
  public const string Example = "hello World";
}
```

Becomes

```
declare class Example {
    public example: string;
}
```

**Comment by andry-tino** [comment]
Treating this as an enhancement, the feature is completely missing.

## Implementation
Suggested approach is doing as in 9dbdd84fbbe8a860a4aca4ddffe8a90c929c963e. Acting at helper level (only for ScriptSharp definition helpers) in order to detect the attribute. This means that a `SemanticModel` will be necessary.

### Effort
Move existing ScriptSharp name adaptation from Translation Unit level to Helper level and add specifc helpers for detecting the attribute.

## Running
@guidoren: The feature, has to rely on the `SemanticModel`, thus you will need to provide an assembly (via the `--assembly` flag in the runner) when calling Rosetta.

**Comment by andry-tino** [comment]
@guidoren: Merry XMas :)
